name: Test

on:
  push:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile --ignore-scripts
      # There's no need to format check on all platforms.
      # + it crashes on windows for some reason not worth investigating.
      - run: bunx nx format:check
        if: matrix.os == 'ubuntu-latest'
      - run: bunx nx run-many -t build lint test
